import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/assets/css/webfont.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frontder",
  description: "Generated by create next app",
};

// https://nextjs.org/docs/app/getting-started/project-structure#examples
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scrollbar-gutter-both`}
    >
      <body className="bg-black text-white max-w-7xl mx-auto px-4">
        <nav className="text-xl font-bold border-b py-2 text-center mb-4">
          <p>Frontder | Frontend Mentor Web Scraping</p>
        </nav>
        {children}
        <ToastContainer
          stacked
          position="bottom-right"
          transition={undefined}
          theme="dark"
        />
      </body>
    </html>
  );
}
