import type { Project } from "./types";

export const projects: Project[] = [
  {
    title: "TM10YMhp - Links",
    desc: "Este clon de linktree obtiene los enlaces desde un google sheet y se actualiza a demanda usando NextJS",
    img: "/projects/next2.webp",
    link: "https://tm10ymhp-links.vercel.app/",
    github: "https://github.com/TM10YMhp/tm10ymhp-links",
    tags: ["React", "NextJS", "TailwindCSS", "CSS", "Google Sheets"],
  },
  {
    title: "Markdown Editor",
    desc: "Un editor de markdown para crear documentos de forma rápida y sencilla. Esta descripcion lo hizo supermaven por cierto.",
    img: "/projects/md_editor.webp",
    link: "https://markdown-editor-311416.netlify.app/",
    github: "https://github.com/TM10YMhp/markdown-editor",
    tags: ["React", "CodeMirror"],
  },
  {
    title: "WA - Chat en Tiempo Real",
    desc: "Mensajes en tiempo real de la forma mas simple que se me hizo posible, gracias a typescript y turborepo.",
    img: "/projects/wa.webp",
    link: "https://wa-client.onrender.com/",
    github: "https://github.com/TM10YMhp/wa_monorepo",
    tags: ["TypeScript", "Workspaces", "Turborepo", "TailwindCSS", "SocketIO"],
  },
  {
    title: "CompressWebp",
    desc: "El script mas simple y estable que tengo hasta ahora. sirve para optimizar imagenes, es muy facil de integrar y muy conveniente por cierto.",
    img: "/projects/compress.webp",
    // link: "",
    // github: "",
    tags: ["Node", "CLI", "Sharp"],
  },
  {
    title: "ff_components",
    desc: "Libreria de componentes para React, usada en un proyecto para Fisiom Fulness.",
    img: "/projects/fisio.webp",
    // link: "",
    // github: "",
    tags: ["React", "NextJS", "TailwindCSS"],
  },
  {
    title: "Pagina Web Responsiva",
    desc: "Pagina adaptada para todos los dispositivos, tambien agregue optimizacion de imagenes.",
    img: "/projects/responsive2.webp",
    // link: "",
    // github: "",
    tags: ["HTML", "CSS", "Javascript", "Wordpress", "Vue", "Alpine"],
  },
  {
    title: "Libros de Diemon",
    desc: 'Muestra los libros de diemon que tiene en el "Google Drive", o al menos eso quisiera... aun en progreso.',
    img: "/projects/diemon.webp",
    link: "https://librosdiemon.netlify.app/",
    github: "https://github.com/TM10YMhp/libros_diemon",
    tags: ["React", "NextJS", "SSR", "API"],
  },
  {
    title: "SereneNvim",
    desc: "Soluciona problemas de compatibilidad con Windows. Mi herramienta preferida para trabajar con Lua, TypeScript, Python, y... Java?. Sigo mejorando el soporte para Java, C++, C# y PHP.",
    img: "/projects/serene.webp",
    // link: "",
    github: "https://github.com/TM10YMhp/init.lua/tree/test",
    tags: ["Lua", "Neovim", "Windows", "Linux"],
  },
  {
    title: "RPG",
    desc: "Un juego que realize en Java y luego pase a Python... el rendimiento disminuyo sorprendentemente.",
    img: "/projects/rpg.gif",
    // link: "",
    // github: "",
    tags: ["Java", "Python"],
  },
  {
    title: "Donut.rs",
    desc: "Una dona que gira sobre su propio eje... hecho con Rust... y trigonometria...",
    img: "/projects/donut.webp",
    // link: "",
    // github: "",
    tags: ["Rust"],
  },
];
